using System.Globalization;
using System.Text;
using System.Text.Json;
using CodeBridge.Flow.Execution;
using CodeBridge.Flow.Validation;

namespace CodeBridge.Flow.CodeGeneration;

/// <summary>What the exported code looks like.</summary>
public enum FlowCSharpMode
{
    /// <summary>A static class with <c>RunAsync(IBoard board, CancellationToken ct)</c> to drop into any project.</summary>
    Class,

    /// <summary>A complete <c>Program.cs</c> (top-level statements) that connects to the board and runs the flow.</summary>
    ConsoleApp
}

public sealed class FlowCSharpOptions
{
    /// <summary>Name of the generated class. Defaults to the flow name plus "Flow".</summary>
    public string? ClassName { get; init; }

    public string Namespace { get; init; } = "CodeBridge.Flows";

    public FlowCSharpMode Mode { get; init; } = FlowCSharpMode.Class;

    /// <summary>Repeat the flow until cancelled, like the Loop checkbox of the designer.</summary>
    public bool Loop { get; init; }

    public int LoopIntervalMs { get; init; } = 1000;
}

public sealed class FlowCSharpResult
{
    public FlowCSharpResult(string code, string className, IReadOnlyList<string> warnings)
    {
        Code = code;
        ClassName = className;
        Warnings = warnings;
    }

    public string Code { get; }
    public string ClassName { get; }

    /// <summary>Blocks that could not be exported (they appear as TODO comments in the code).</summary>
    public IReadOnlyList<string> Warnings { get; }
}

/// <summary>
/// Turns a visual flow into readable C# that behaves like the flow runtime: blocks run in dependency order, a block
/// whose trigger input is connected only runs when one of its triggers fired, and data wires become local variables.
/// </summary>
public static class FlowCSharpGenerator
{
    public static FlowCSharpResult Generate(FlowDocument document, FlowCSharpOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(document);
        options ??= new FlowCSharpOptions();

        var profile = BuiltInBoardProfiles.FindById(document.BoardId) ?? BuiltInBoardProfiles.Default;
        var catalog = BuiltInBlockCatalog.Create(profile);

        var validation = new FlowValidator().Validate(document, catalog);
        if (!validation.IsValid)
        {
            throw new InvalidOperationException(
                "The flow has errors and cannot be exported:" + Environment.NewLine +
                string.Join(Environment.NewLine, validation.Errors.Select(issue => "- " + issue.Message)));
        }

        return new Writer(document, catalog, profile, options).Write();
    }

    private sealed class Writer
    {
        private readonly FlowDocument _document;
        private readonly FlowBlockCatalog _catalog;
        private readonly BoardProfile _profile;
        private readonly FlowCSharpOptions _options;
        private readonly StringBuilder _code = new();
        private readonly List<string> _warnings = new();
        private readonly Dictionary<string, string> _names = new(StringComparer.OrdinalIgnoreCase);
        private int _indent;
        private bool _declareOnAssign;
        private FlowBlockDefinition? _current;

        public Writer(FlowDocument document, FlowBlockCatalog catalog, BoardProfile profile, FlowCSharpOptions options)
        {
            _document = document;
            _catalog = catalog;
            _profile = profile;
            _options = options;
        }

        public FlowCSharpResult Write()
        {
            var ordered = FlowGraphSorter.Sort(_document);
            AssignNames(ordered);

            var className = Identifier(_options.ClassName ?? (_document.Name + "Flow"), "Flow");
            var usesServo = ordered.Any(node => node.Type == BuiltInBlockCatalog.ServoWrite);
            var isArduino = string.Equals(_profile.Id, BuiltInBoardProfiles.ArduinoUno.Id, StringComparison.OrdinalIgnoreCase);

            var body = new Writer(_document, _catalog, _profile, _options) { _indent = 0 };
            body.CopyNames(_names);
            body.WriteBody(ordered, usesServo);
            _warnings.AddRange(body._warnings);

            var bodyText = body._code.ToString();
            if (!bodyText.Contains("await "))
                bodyText = "await Task.CompletedTask; // nothing to await in this flow" + Environment.NewLine + bodyText;

            Line("// <auto-generated>");
            Line($"//   Exported from the CodeBridge flow \"{_document.Name}\" (board: {_profile.DisplayName}).");
            Line("//   Edit freely: it is plain C# on top of the CodeBridge SDK (dotnet add package CodeBridge.ESP32).");
            Line("// </auto-generated>");
            Line("using System;");
            Line("using System.Linq;");
            Line("using System.Threading;");
            Line("using System.Threading.Tasks;");
            Line("using CodeBridge.Core;");
            Line("using CodeBridge.Core.Abstractions;");
            Line("using CodeBridge.Core.Enums;");
            Line("using CodeBridge.ESP32;");
            if (_options.Mode == FlowCSharpMode.ConsoleApp)
            {
                Line("using CodeBridge.Transport;");
                if (isArduino)
                    Line("using CodeBridge.Transport.Serial;");
            }

            Line();

            if (_options.Mode == FlowCSharpMode.ConsoleApp)
            {
                WriteProgram(className, isArduino);
                Line();
                WriteClass(className, bodyText, namespaced: false);
            }
            else
            {
                Line($"namespace {_options.Namespace};");
                Line();
                WriteClass(className, bodyText, namespaced: true);
            }

            return new FlowCSharpResult(_code.ToString(), className, _warnings);
        }

        // ------------------------------------------------------------------ program / class frame

        private void WriteProgram(string className, bool isArduino)
        {
            Line("// Usage: dotnet run -- COM3     (omit the port to use the first board found)");
            Line("var port = args.Length > 0 ? args[0] : BoardDiscovery.DiscoverPorts().FirstOrDefault()?.Name;");
            Line("if (port is null)");
            Line("{");
            Line("    Console.WriteLine(\"No board found. Plug it in or pass the port: dotnet run -- COM3\");");
            Line("    return 1;");
            Line("}");
            Line();
            Line("using var cancel = new CancellationTokenSource();");
            Line("Console.CancelKeyPress += (_, e) => { e.Cancel = true; cancel.Cancel(); };");
            Line();
            Line("Console.WriteLine($\"Connecting to {port}...\");");
            if (isArduino)
            {
                Line("await using var board = new CodeBridgeProtocolBoard(new SerialTransport(port), \"Arduino Uno\", BoardFamily.Arduino);");
                Line("await board.ConnectAsync(cancel.Token);");
            }
            else
            {
                Line("await using var board = await CodeBridgeBuilder.Connect().Serial(port).ToESP32().BuildAsync(cancel.Token);");
            }

            Line("Console.WriteLine($\"Connected. Firmware {board.FirmwareVersion}.\");");
            Line();
            Line("try");
            Line("{");
            Line($"    await {className}.RunAsync(board, cancel.Token);");
            Line("}");
            Line("catch (OperationCanceledException)");
            Line("{");
            Line("    // Ctrl+C");
            Line("}");
            Line();
            Line("return 0;");
        }

        private void WriteClass(string className, string body, bool namespaced)
        {
            Line($"/// <summary>The flow \"{_document.Name}\" as C#.</summary>");
            Line($"public static class {className}");
            Line("{");
            Line("    public static async Task RunAsync(IBoard board, CancellationToken ct = default)");
            Line("    {");
            foreach (var line in body.TrimEnd().Split(new[] { Environment.NewLine }, StringSplitOptions.None))
                _code.AppendLine(line.Length == 0 ? string.Empty : "        " + line);

            Line("    }");
            Line("}");
        }

        private void CopyNames(Dictionary<string, string> names)
        {
            foreach (var pair in names)
                _names[pair.Key] = pair.Value;
        }

        // ------------------------------------------------------------------ flow body

        private void WriteBody(IReadOnlyList<FlowNode> ordered, bool usesServo)
        {
            if (usesServo)
            {
                Line("var esp32 = board as ESP32Board ?? throw new NotSupportedException(\"Servo blocks need an ESP32 board.\");");
                Line();
            }

            if (_options.Loop)
            {
                Line("do");
                Line("{");
                _indent++;
            }

            foreach (var node in ordered)
            {
                WriteNode(node);
                Line();
            }

            if (_options.Loop)
            {
                Line($"if (!ct.IsCancellationRequested)");
                Line($"    await Task.Delay({_options.LoopIntervalMs}, ct);");
                _indent--;
                Line("} while (!ct.IsCancellationRequested);");
            }
            else
            {
                TrimTrailingBlankLine();
            }
        }

        private void WriteNode(FlowNode node)
        {
            var definition = _catalog.Get(node.Type);
            var name = _names[node.Id];
            Line($"// {definition.DisplayName} ({name})");

            var run = TriggerExpression(node, definition);
            var conditional = run != "true";

            _current = definition;
            _declareOnAssign = !conditional;

            // For blocks that may be skipped, outputs something downstream reads are declared up front at their default.
            if (conditional)
            {
                foreach (var port in definition.OutputPorts.Where(p => IsUsed(node, p.Name)))
                    Line($"{TypeOf(port.ValueKind)} {Var(node, port.Name)} = {DefaultOf(port.ValueKind)};");
            }

            if (conditional)
            {
                Line($"if ({run})");
                Line("{");
                _indent++;
            }

            WriteBlock(node, definition);

            if (conditional)
            {
                _indent--;
                Line("}");
            }
        }

        private void WriteBlock(FlowNode node, FlowBlockDefinition definition)
        {
            var pin = () => ParamInt(node, definition, "pin");
            switch (node.Type)
            {
                case BuiltInBlockCatalog.ManualTrigger:
                    Assign(node, "trigger", "true");
                    break;

                case BuiltInBlockCatalog.Timer:
                    Line($"await Task.Delay({ParamInt(node, definition, "intervalMs")}, ct);");
                    Assign(node, "tick", "true");
                    break;

                case BuiltInBlockCatalog.ConstantBoolean:
                    Assign(node, "value", Bool(ParamBool(node, definition, "value")));
                    break;

                case BuiltInBlockCatalog.ConstantNumber:
                    Assign(node, "value", Double(ParamDouble(node, definition, "value")));
                    break;

                case BuiltInBlockCatalog.Compare:
                {
                    var left = $"(double){InputExpression(node, "left", "0.0")}";
                    var right = $"(double){InputExpression(node, "right", "0.0")}";
                    var op = ParamString(node, definition, "operator");
                    var expression = op switch
                    {
                        ">" or ">=" or "<" or "<=" => $"{left} {op} {right}",
                        "==" => $"Math.Abs({left} - {right}) < double.Epsilon",
                        "!=" => $"Math.Abs({left} - {right}) >= double.Epsilon",
                        _ => throw new InvalidOperationException($"Unsupported compare operator '{op}'.")
                    };
                    Assign(node, "result", expression);
                    break;
                }

                case BuiltInBlockCatalog.GpioPinMode:
                    Line($"await board.Gpio.SetPinModeAsync({pin()}, PinMode.{PinModeName(ParamString(node, definition, "mode"))}, ct);");
                    Assign(node, "done", "true");
                    break;

                case BuiltInBlockCatalog.GpioDigitalRead:
                    Assign(node, "value", $"await board.Gpio.DigitalReadAsync({pin()}, ct) == PinValue.High");
                    break;

                case BuiltInBlockCatalog.GpioAnalogRead:
                    Assign(node, "value", $"await board.Gpio.AnalogReadAsync({pin()}, ct)");
                    break;

                case BuiltInBlockCatalog.GpioDigitalWrite:
                {
                    // Same rule as the runtime: the pin becomes an output unless another block already configures it.
                    if (!IsPinConfiguredByBlock(pin()))
                        Line($"await board.Gpio.SetPinModeAsync({pin()}, PinMode.Output, ct);");

                    var literal = Bool(ParamBool(node, definition, "value"));
                    var value = InputExpression(node, "value", literal);
                    var level = HasConnection(node, "value") ? $"{value} ? PinValue.High : PinValue.Low" : (literal == "true" ? "PinValue.High" : "PinValue.Low");
                    Line($"await board.Gpio.DigitalWriteAsync({pin()}, {level}, ct);");
                    Assign(node, "done", "true");
                    Assign(node, "value", value);
                    break;
                }

                case BuiltInBlockCatalog.GpioSetOutput:
                {
                    var requested = ParamBool(node, definition, "value");
                    var output = ParamBool(node, definition, "activeLow") ? !requested : requested;
                    Line($"await board.Gpio.SetPinModeAsync({pin()}, PinMode.Output, ct);");
                    Line($"await board.Gpio.DigitalWriteAsync({pin()}, PinValue.{(output ? "High" : "Low")}, ct);");
                    Assign(node, "done", "true");
                    Assign(node, "value", Bool(requested));
                    Assign(node, "pin", pin().ToString(CultureInfo.InvariantCulture));
                    break;
                }

                case BuiltInBlockCatalog.GpioBlinkLed:
                {
                    var duration = Math.Max(0, ParamInt(node, definition, "durationMs"));
                    var activeLow = ParamBool(node, definition, "activeLow");
                    var leaveOn = ParamBool(node, definition, "leaveOn");
                    var on = activeLow ? "Low" : "High";
                    var off = activeLow ? "High" : "Low";

                    Line($"await board.Gpio.SetPinModeAsync({pin()}, PinMode.Output, ct);");
                    Line($"await board.Gpio.DigitalWriteAsync({pin()}, PinValue.{on}, ct);");
                    if (duration > 0)
                        Line($"await Task.Delay({duration}, ct);");

                    if (!leaveOn)
                        Line($"await board.Gpio.DigitalWriteAsync({pin()}, PinValue.{off}, ct);");

                    Assign(node, "done", "true");
                    Assign(node, "pin", pin().ToString(CultureInfo.InvariantCulture));
                    Assign(node, "durationMs", duration.ToString(CultureInfo.InvariantCulture));
                    Assign(node, "value", Bool(leaveOn));
                    break;
                }

                case BuiltInBlockCatalog.ServoWrite:
                {
                    var servo = _names[node.Id] + "Servo";
                    var angle = InputExpression(node, "angle", Double(ParamDouble(node, definition, "angle")));
                    Line($"var {servo} = esp32.CreateServo({pin()}, {ParamInt(node, definition, "minPulseUs")}, {ParamInt(node, definition, "maxPulseUs")});");
                    Line($"await {servo}.InitAsync(ct);");
                    Line($"await {servo}.SetAngleAsync((int)Math.Round(Math.Clamp((double){angle}, 0, 180)), ct);");
                    Assign(node, "done", "true");
                    break;
                }

                case BuiltInBlockCatalog.DebugLog:
                {
                    var label = ParamString(node, definition, "label");
                    var fallback = ParamString(node, definition, "message");
                    string message;
                    if (HasConnection(node, "value"))
                        message = $"FormattableString.Invariant($\"{EscapeInterpolated(label)}: {{{DebugValue(node)}}}\")";
                    else
                        message = StringLiteral(string.IsNullOrWhiteSpace(fallback) ? label : fallback);

                    if (IsUsed(node, "message"))
                        Line($"{Var(node, "message")} = {message};");
                    else
                        Line($"var {_names[node.Id]}Message = {message};");

                    Line($"Console.WriteLine({(IsUsed(node, "message") ? Var(node, "message") : _names[node.Id] + "Message")});");
                    Assign(node, "done", "true");
                    break;
                }

                default:
                    Line($"// TODO: the \"{definition.DisplayName}\" block has no C# export yet. Use the SDK directly");
                    Line("// (board.Gpio, board.Acquisition, ...) or keep running this flow with the designer.");
                    _warnings.Add($"The \"{definition.DisplayName}\" block ({node.Id}) is not exported; a TODO comment was written instead.");
                    break;
            }
        }

        // ------------------------------------------------------------------ emitting helpers

        private void Assign(FlowNode node, string port, string expression)
        {
            if (!IsUsed(node, port))
            {
                // Evaluate for side effects only when the expression is an await (reads must still happen).
                if (expression.StartsWith("await ", StringComparison.Ordinal))
                    Line($"_ = {expression};");

                return;
            }

            if (_declareOnAssign && _current?.FindOutput(port) is { } output)
                Line($"{TypeOf(output.ValueKind)} {Var(node, port)} = {expression};");
            else
                Line($"{Var(node, port)} = {expression};");
        }

        private string TriggerExpression(FlowNode node, FlowBlockDefinition definition)
        {
            var triggerPorts = definition.InputPorts.Where(p => p.ValueKind == FlowValueKind.Trigger).ToList();
            if (triggerPorts.Count == 0)
                return "true";

            var connected = _document.Connections
                .Where(c => string.Equals(c.ToNodeId, node.Id, StringComparison.OrdinalIgnoreCase) &&
                            triggerPorts.Any(p => string.Equals(p.Name, c.ToPort, StringComparison.OrdinalIgnoreCase)))
                .Select(c => SourceVar(c))
                .Distinct()
                .ToList();

            return connected.Count == 0 ? "true" : string.Join(" || ", connected);
        }

        private string InputExpression(FlowNode node, string portName, string fallback)
        {
            var connection = _document.Connections.FirstOrDefault(c =>
                string.Equals(c.ToNodeId, node.Id, StringComparison.OrdinalIgnoreCase) &&
                string.Equals(c.ToPort, portName, StringComparison.OrdinalIgnoreCase));

            return connection == null ? fallback : SourceVar(connection);
        }

        /// <summary>The wired value formatted like the runtime does (true/false in lower case, invariant numbers).</summary>
        private string DebugValue(FlowNode node)
        {
            var connection = _document.Connections.First(c =>
                string.Equals(c.ToNodeId, node.Id, StringComparison.OrdinalIgnoreCase) &&
                string.Equals(c.ToPort, "value", StringComparison.OrdinalIgnoreCase));
            var source = _document.Nodes.First(n => string.Equals(n.Id, connection.FromNodeId, StringComparison.OrdinalIgnoreCase));
            var kind = _catalog.Get(source.Type).FindOutput(connection.FromPort)?.ValueKind ?? FlowValueKind.Any;
            var variable = SourceVar(connection);
            return kind is FlowValueKind.Boolean or FlowValueKind.Trigger ? $"({variable} ? \"true\" : \"false\")" : variable;
        }

        private bool HasConnection(FlowNode node, string portName) =>
            _document.Connections.Any(c =>
                string.Equals(c.ToNodeId, node.Id, StringComparison.OrdinalIgnoreCase) &&
                string.Equals(c.ToPort, portName, StringComparison.OrdinalIgnoreCase));

        private bool IsUsed(FlowNode node, string port) =>
            _document.Connections.Any(c =>
                string.Equals(c.FromNodeId, node.Id, StringComparison.OrdinalIgnoreCase) &&
                string.Equals(c.FromPort, port, StringComparison.OrdinalIgnoreCase));

        private string SourceVar(FlowConnection connection)
        {
            var source = _document.Nodes.First(n => string.Equals(n.Id, connection.FromNodeId, StringComparison.OrdinalIgnoreCase));
            return Var(source, connection.FromPort);
        }

        private string Var(FlowNode node, string port) => _names[node.Id] + char.ToUpperInvariant(port[0]) + port.Substring(1);

        private bool IsPinConfiguredByBlock(int pin) =>
            _document.Nodes.Any(node =>
                (node.Type == BuiltInBlockCatalog.GpioPinMode || node.Type == BuiltInBlockCatalog.GpioSetOutput || node.Type == BuiltInBlockCatalog.GpioBlinkLed) &&
                node.Parameters.TryGetValue("pin", out var value) &&
                TryInt(value, out var configured) && configured == pin);

        private void AssignNames(IReadOnlyList<FlowNode> ordered)
        {
            var counters = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
            foreach (var node in ordered)
            {
                var shortName = node.Type.Substring(node.Type.LastIndexOf('.') + 1);
                var parts = shortName.Split('-');
                var camel = parts[0] + string.Concat(parts.Skip(1).Select(p => char.ToUpperInvariant(p[0]) + p.Substring(1)));
                counters.TryGetValue(camel, out var count);
                counters[camel] = ++count;
                _names[node.Id] = camel + count.ToString(CultureInfo.InvariantCulture);
            }
        }

        private void TrimTrailingBlankLine()
        {
            while (_code.Length >= 2 * Environment.NewLine.Length &&
                   _code.ToString(_code.Length - 2 * Environment.NewLine.Length, 2 * Environment.NewLine.Length) == Environment.NewLine + Environment.NewLine)
            {
                _code.Length -= Environment.NewLine.Length;
            }
        }

        private void Line(string text = "")
        {
            if (text.Length == 0)
                _code.AppendLine();
            else
                _code.AppendLine(new string(' ', _indent * 4) + text);
        }

        // ------------------------------------------------------------------ parameters and literals

        private static object? Raw(FlowNode node, FlowBlockDefinition definition, string name)
        {
            if (node.Parameters.TryGetValue(name, out var value) && value != null)
                return value;

            return definition.FindProperty(name)?.DefaultValue;
        }

        private static int ParamInt(FlowNode node, FlowBlockDefinition definition, string name) =>
            TryInt(Raw(node, definition, name), out var value) ? value : 0;

        private static double ParamDouble(FlowNode node, FlowBlockDefinition definition, string name)
        {
            var raw = Raw(node, definition, name);
            return raw switch
            {
                JsonElement json when json.ValueKind == JsonValueKind.Number => json.GetDouble(),
                null => 0,
                _ => Convert.ToDouble(raw, CultureInfo.InvariantCulture)
            };
        }

        private static bool ParamBool(FlowNode node, FlowBlockDefinition definition, string name)
        {
            var raw = Raw(node, definition, name);
            return raw switch
            {
                bool flag => flag,
                JsonElement json when json.ValueKind == JsonValueKind.True => true,
                JsonElement json when json.ValueKind == JsonValueKind.False => false,
                null => false,
                _ => Convert.ToBoolean(raw, CultureInfo.InvariantCulture)
            };
        }

        private static string ParamString(FlowNode node, FlowBlockDefinition definition, string name)
        {
            var raw = Raw(node, definition, name);
            return raw switch
            {
                JsonElement json when json.ValueKind == JsonValueKind.String => json.GetString() ?? string.Empty,
                null => string.Empty,
                _ => Convert.ToString(raw, CultureInfo.InvariantCulture) ?? string.Empty
            };
        }

        private static bool TryInt(object? raw, out int value)
        {
            switch (raw)
            {
                case int i:
                    value = i;
                    return true;
                case JsonElement json when json.ValueKind == JsonValueKind.Number && json.TryGetInt32(out var j):
                    value = j;
                    return true;
                case null:
                    value = 0;
                    return false;
                default:
                    try
                    {
                        value = Convert.ToInt32(raw, CultureInfo.InvariantCulture);
                        return true;
                    }
                    catch (Exception ex) when (ex is FormatException or InvalidCastException or OverflowException)
                    {
                        value = 0;
                        return false;
                    }
            }
        }

        private static string Bool(bool value) => value ? "true" : "false";

        private static string Double(double value) => value.ToString("0.0###############", CultureInfo.InvariantCulture);

        private static string StringLiteral(string value) =>
            "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n") + "\"";

        private static string EscapeInterpolated(string value) =>
            value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("{", "{{").Replace("}", "}}");

        private static string PinModeName(string mode)
        {
            var normalized = mode.Trim().Replace("-", string.Empty).ToLowerInvariant();
            return normalized switch
            {
                "input" or "in" or "0" => "Input",
                "output" or "out" or "1" => "Output",
                "inputpullup" or "pullup" or "2" => "InputPullUp",
                "inputpulldown" or "pulldown" or "3" => "InputPullDown",
                "analog" or "adc" or "4" => "Analog",
                _ => throw new InvalidOperationException($"Unsupported pin mode '{mode}'.")
            };
        }

        private static string TypeOf(FlowValueKind kind) => kind switch
        {
            FlowValueKind.Trigger or FlowValueKind.Boolean => "bool",
            FlowValueKind.Integer => "int",
            FlowValueKind.Number => "double",
            FlowValueKind.String => "string",
            _ => "object?"
        };

        private static string DefaultOf(FlowValueKind kind) => kind switch
        {
            FlowValueKind.Trigger or FlowValueKind.Boolean => "false",
            FlowValueKind.Integer => "0",
            FlowValueKind.Number => "0.0",
            FlowValueKind.String => "string.Empty",
            _ => "null"
        };

        private static string Identifier(string text, string fallback)
        {
            var builder = new StringBuilder();
            var upperNext = true;
            foreach (var ch in text)
            {
                if (char.IsLetterOrDigit(ch) || ch == '_')
                {
                    builder.Append(upperNext ? char.ToUpperInvariant(ch) : ch);
                    upperNext = false;
                }
                else
                {
                    upperNext = true;
                }
            }

            var result = builder.ToString();
            if (result.Length == 0)
                return fallback;

            return char.IsDigit(result[0]) ? "Flow" + result : result;
        }
    }
}
