<Project>
  <PropertyGroup>
    <Version>0.1.17-preview.1</Version>
    <Authors>CodeBridge</Authors>
    <Company>CodeBridge</Company>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>codebridge;esp32;arduino;iot;winforms;visual-flow</PackageTags>
  </PropertyGroup>

  <ItemGroup Condition="Exists('$(MSBuildThisFileDirectory)README.md')">
    <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>
</Project>
