using System.Text;

namespace CodeBridge.VisualStudio;

internal static class CodeBridgeStarterFormTemplate
{
    public static string Create(string namespaceName, string className)
    {
        var builder = new StringBuilder();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Drawing;");
        builder.AppendLine("using System.Globalization;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("using System.Windows.Forms;");
        builder.AppendLine("using CodeBridge.Designer.WinForms;");
        builder.AppendLine("using CodeBridge.Flow;");
        builder.AppendLine("using CodeBridge.Flow.Execution;");
        builder.AppendLine("using CodeBridge.Transport;");
        builder.AppendLine();
        builder.AppendLine($"namespace {namespaceName}");
        builder.AppendLine("{");
        builder.AppendLine($"    public sealed class {className} : Form");
        builder.AppendLine("    {");
        builder.AppendLine("        private readonly CodeBridgeBoardComponent _board = new();");
        builder.AppendLine("        private readonly CodeBridgeFlowControl _flow = new();");
        builder.AppendLine("        private readonly ComboBox _portInput = new();");
        builder.AppendLine("        private readonly NumericUpDown _baudRateInput = new();");
        builder.AppendLine("        private readonly ComboBox _pinInput = new();");
        builder.AppendLine("        private readonly Button _refreshButton = new();");
        builder.AppendLine("        private readonly Button _connectButton = new();");
        builder.AppendLine("        private readonly Button _uploadButton = new();");
        builder.AppendLine("        private readonly Button _editButton = new();");
        builder.AppendLine("        private readonly Button _presetButton = new();");
        builder.AppendLine("        private readonly Button _runButton = new();");
        builder.AppendLine("        private readonly Button _stopButton = new();");
        builder.AppendLine("        private readonly TextBox _log = new();");
        builder.AppendLine("        private bool _closing;");
        builder.AppendLine();
        builder.AppendLine($"        public {className}()");
        builder.AppendLine("        {");
        builder.AppendLine("            Text = \"CodeBridge Board Starter\";");
        builder.AppendLine("            StartPosition = FormStartPosition.CenterScreen;");
        builder.AppendLine("            MinimumSize = new Size(860, 520);");
        builder.AppendLine("            Size = new Size(980, 580);");
        builder.AppendLine("            Font = new Font(\"Segoe UI\", 9F);");
        builder.AppendLine("            BackColor = Color.FromArgb(246, 247, 248);");
        builder.AppendLine();
        builder.AppendLine("            BuildLayout();");
        builder.AppendLine("            PopulatePins();");
        builder.AppendLine("            WireEvents();");
        builder.AppendLine("            LoadBlinkFlow();");
        builder.AppendLine("            RefreshPorts();");
        builder.AppendLine("            UpdateState();");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private void BuildLayout()");
        builder.AppendLine("        {");
        builder.AppendLine("            var root = new TableLayoutPanel { Dock = DockStyle.Fill, ColumnCount = 2, Padding = new Padding(14) };");
        builder.AppendLine("            root.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 280));");
        builder.AppendLine("            root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));");
        builder.AppendLine();
        builder.AppendLine("            var left = new TableLayoutPanel { Dock = DockStyle.Fill, ColumnCount = 2, RowCount = 10, Padding = new Padding(0, 0, 14, 0) };");
        builder.AppendLine("            left.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 72));");
        builder.AppendLine("            left.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));");
        builder.AppendLine();
        builder.AppendLine("            _portInput.DropDownStyle = ComboBoxStyle.DropDown;");
        builder.AppendLine("            _baudRateInput.Minimum = 9600;");
        builder.AppendLine("            _baudRateInput.Maximum = 921600;");
        builder.AppendLine("            _baudRateInput.Increment = 9600;");
        builder.AppendLine("            _baudRateInput.Value = 115200;");
        builder.AppendLine("            _pinInput.DropDownStyle = ComboBoxStyle.DropDownList;");
        builder.AppendLine();
        builder.AppendLine("            ConfigureButton(_refreshButton, \"Refresh\");");
        builder.AppendLine("            ConfigureButton(_connectButton, \"Connect\");");
        builder.AppendLine("            ConfigureButton(_uploadButton, \"Upload FW\");");
        builder.AppendLine("            ConfigureButton(_editButton, \"Edit Flow\");");
        builder.AppendLine("            ConfigureButton(_presetButton, \"Preset\");");
        builder.AppendLine("            ConfigureButton(_runButton, \"Run Blink\");");
        builder.AppendLine("            ConfigureButton(_stopButton, \"Stop\");");
        builder.AppendLine();
        builder.AppendLine("            AddRow(left, 0, \"Port\", _portInput);");
        builder.AppendLine("            AddRow(left, 1, \"Baud\", _baudRateInput);");
        builder.AppendLine("            AddRow(left, 2, \"GPIO\", _pinInput);");
        builder.AppendLine("            AddRow(left, 3, string.Empty, _refreshButton);");
        builder.AppendLine("            AddRow(left, 4, string.Empty, _connectButton);");
        builder.AppendLine("            AddRow(left, 5, string.Empty, _uploadButton);");
        builder.AppendLine("            AddRow(left, 6, string.Empty, _editButton);");
        builder.AppendLine("            AddRow(left, 7, string.Empty, _presetButton);");
        builder.AppendLine("            AddRow(left, 8, string.Empty, _runButton);");
        builder.AppendLine("            AddRow(left, 9, string.Empty, _stopButton);");
        builder.AppendLine();
        builder.AppendLine("            var right = new TableLayoutPanel { Dock = DockStyle.Fill, RowCount = 3 };");
        builder.AppendLine("            right.RowStyles.Add(new RowStyle(SizeType.Absolute, 86));");
        builder.AppendLine("            right.RowStyles.Add(new RowStyle(SizeType.Absolute, 8));");
        builder.AppendLine("            right.RowStyles.Add(new RowStyle(SizeType.Percent, 100));");
        builder.AppendLine();
        builder.AppendLine("            _flow.Dock = DockStyle.Fill;");
        builder.AppendLine("            _flow.TraceDelayMs = 120;");
        builder.AppendLine("            _log.Dock = DockStyle.Fill;");
        builder.AppendLine("            _log.Multiline = true;");
        builder.AppendLine("            _log.ReadOnly = true;");
        builder.AppendLine("            _log.ScrollBars = ScrollBars.Vertical;");
        builder.AppendLine("            _log.Font = new Font(\"Consolas\", 9F);");
        builder.AppendLine("            _log.BackColor = Color.FromArgb(30, 34, 37);");
        builder.AppendLine("            _log.ForeColor = Color.FromArgb(235, 238, 236);");
        builder.AppendLine();
        builder.AppendLine("            right.Controls.Add(_flow, 0, 0);");
        builder.AppendLine("            right.Controls.Add(_log, 0, 2);");
        builder.AppendLine("            root.Controls.Add(left, 0, 0);");
        builder.AppendLine("            root.Controls.Add(right, 1, 0);");
        builder.AppendLine("            Controls.Add(root);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private void WireEvents()");
        builder.AppendLine("        {");
        builder.AppendLine("            _refreshButton.Click += (_, _) => RefreshPorts();");
        builder.AppendLine("            _connectButton.Click += async (_, _) => await ConnectAsync();");
        builder.AppendLine("            _uploadButton.Click += async (_, _) => await UploadFirmwareAsync();");
        builder.AppendLine("            _editButton.Click += (_, _) => _flow.ShowEditor(_board, this);");
        builder.AppendLine("            _presetButton.Click += (_, _) => _flow.ShowPresetDialog(this);");
        builder.AppendLine("            _runButton.Click += async (_, _) => await RunAsync();");
        builder.AppendLine("            _stopButton.Click += (_, _) => _flow.Stop();");
        builder.AppendLine("            _pinInput.SelectedIndexChanged += (_, _) => LoadBlinkFlow();");
        builder.AppendLine("            _board.BoardId = BuiltInBoardProfiles.Esp32DevKit.Id;");
        builder.AppendLine("            _board.Connected += (_, _) => AppendLog(_board.BoardName + \" connected.\");");
        builder.AppendLine("            _board.Disconnected += (_, _) => AppendLog(_board.BoardName + \" disconnected.\");");
        builder.AppendLine("            _board.ConnectionFailed += (_, ex) => AppendLog(\"Connection failed: \" + ex.Message);");
        builder.AppendLine("            _flow.FlowStarted += (_, _) => AppendLog(\"Flow started.\");");
        builder.AppendLine("            _flow.FlowCompleted += (_, result) => AppendLog($\"Flow completed. Nodes: {result.NodeOutputs.Count}\");");
        builder.AppendLine("            _flow.FlowFailed += (_, ex) => AppendLog(\"Flow failed: \" + ex.Message);");
        builder.AppendLine("            _flow.FlowTrace += (_, trace) => AppendLog($\"{FormatTrace(trace.Kind)} {trace.NodeId}\");");
        builder.AppendLine("            _flow.FlowStopped += (_, _) => UpdateState();");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private void PopulatePins()");
        builder.AppendLine("        {");
        builder.AppendLine("            _pinInput.Items.Clear();");
        builder.AppendLine("            foreach (var option in BuiltInBoardProfiles.Esp32DevKit.DigitalWritePinOptions)");
        builder.AppendLine("                _pinInput.Items.Add(new PinItem(option));");
        builder.AppendLine("            if (_pinInput.Items.Count > 0)");
        builder.AppendLine("                _pinInput.SelectedIndex = 0;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private void RefreshPorts()");
        builder.AppendLine("        {");
        builder.AppendLine("            var selected = _portInput.Text;");
        builder.AppendLine("            _portInput.Items.Clear();");
        builder.AppendLine("            foreach (var port in BoardDiscovery.DiscoverPorts())");
        builder.AppendLine("                _portInput.Items.Add(port.Name);");
        builder.AppendLine("            if (!string.IsNullOrWhiteSpace(selected))");
        builder.AppendLine("                _portInput.Text = selected;");
        builder.AppendLine("            else if (_portInput.Items.Count > 0)");
        builder.AppendLine("                _portInput.SelectedIndex = 0;");
        builder.AppendLine("            AppendLog(_portInput.Items.Count == 0 ? \"No serial ports detected.\" : $\"Detected {_portInput.Items.Count} serial port(s).\");");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private async Task ConnectAsync()");
        builder.AppendLine("        {");
        builder.AppendLine("            SyncConnectionSettings();");
        builder.AppendLine("            UpdateState(connecting: true);");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                await _board.ConnectAsync();");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (Exception ex)");
        builder.AppendLine("            {");
        builder.AppendLine("                MessageBox.Show(this, ex.Message, \"CodeBridge connection\", MessageBoxButtons.OK, MessageBoxIcon.Error);");
        builder.AppendLine("            }");
        builder.AppendLine("            finally");
        builder.AppendLine("            {");
        builder.AppendLine("                UpdateState();");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private async Task UploadFirmwareAsync()");
        builder.AppendLine("        {");
        builder.AppendLine("            SyncConnectionSettings();");
        builder.AppendLine("            UpdateState(connecting: true);");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                var result = await _board.UploadFirmwareAsync();");
        builder.AppendLine("                AppendLog(result.Success ? \"Firmware uploaded. Reconnect after the board restarts.\" : \"Firmware upload failed.\");");
        builder.AppendLine("                if (!result.Success)");
        builder.AppendLine("                    MessageBox.Show(this, result.Log, \"CodeBridge firmware\", MessageBoxButtons.OK, MessageBoxIcon.Error);");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (Exception ex)");
        builder.AppendLine("            {");
        builder.AppendLine("                MessageBox.Show(this, ex.Message, \"CodeBridge firmware\", MessageBoxButtons.OK, MessageBoxIcon.Error);");
        builder.AppendLine("            }");
        builder.AppendLine("            finally");
        builder.AppendLine("            {");
        builder.AppendLine("                UpdateState();");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private async Task RunAsync()");
        builder.AppendLine("        {");
        builder.AppendLine("            SyncConnectionSettings();");
        builder.AppendLine("            UpdateState(running: true);");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                await _board.RunAsync(_flow);");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (Exception ex) when (!_closing)");
        builder.AppendLine("            {");
        builder.AppendLine("                MessageBox.Show(this, ex.Message, \"CodeBridge flow\", MessageBoxButtons.OK, MessageBoxIcon.Error);");
        builder.AppendLine("            }");
        builder.AppendLine("            finally");
        builder.AppendLine("            {");
        builder.AppendLine("                UpdateState();");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private void SyncConnectionSettings()");
        builder.AppendLine("        {");
        builder.AppendLine("            _board.TransportMode = CodeBridgeTransportMode.Serial;");
        builder.AppendLine("            _board.PortName = _portInput.Text.Trim();");
        builder.AppendLine("            _board.BaudRate = (int)_baudRateInput.Value;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private void LoadBlinkFlow()");
        builder.AppendLine("        {");
        builder.AppendLine("            _flow.FlowName = \"ESP32 Blink\";");
        builder.AppendLine("            _flow.ExecutionMode = FlowExecutionMode.Trigger;");
        builder.AppendLine("            _flow.LoadBlinkPreset(SelectedPin, delayMs: 500);");
        builder.AppendLine("            AppendLog($\"Blink preset loaded for GPIO {SelectedPin}.\");");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private void UpdateState(bool connecting = false, bool running = false)");
        builder.AppendLine("        {");
        builder.AppendLine("            var isRunning = running || _flow.IsRunning;");
        builder.AppendLine("            _connectButton.Enabled = !connecting && !_board.IsConnected && !isRunning;");
        builder.AppendLine("            _runButton.Enabled = !connecting && !isRunning;");
        builder.AppendLine("            _stopButton.Enabled = isRunning;");
        builder.AppendLine("            _refreshButton.Enabled = !connecting && !isRunning;");
        builder.AppendLine("            _uploadButton.Enabled = !connecting && !_board.IsConnected && !isRunning;");
        builder.AppendLine("            _portInput.Enabled = !_board.IsConnected && !isRunning;");
        builder.AppendLine("            _baudRateInput.Enabled = !_board.IsConnected && !isRunning;");
        builder.AppendLine("            _pinInput.Enabled = !isRunning;");
        builder.AppendLine("            _editButton.Enabled = !isRunning;");
        builder.AppendLine("            _presetButton.Enabled = !isRunning;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private int SelectedPin => _pinInput.SelectedItem is PinItem item ? item.Number : 2;");
        builder.AppendLine();
        builder.AppendLine("        private static string FormatTrace(FlowExecutionEventKind kind)");
        builder.AppendLine("        {");
        builder.AppendLine("            return kind switch");
        builder.AppendLine("            {");
        builder.AppendLine("                FlowExecutionEventKind.NodeStarted => \"started\",");
        builder.AppendLine("                FlowExecutionEventKind.NodeCompleted => \"completed\",");
        builder.AppendLine("                FlowExecutionEventKind.NodeSkipped => \"skipped\",");
        builder.AppendLine("                FlowExecutionEventKind.NodeFailed => \"failed\",");
        builder.AppendLine("                _ => kind.ToString()");
        builder.AppendLine("            };");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static void AddRow(TableLayoutPanel panel, int row, string label, Control control)");
        builder.AppendLine("        {");
        builder.AppendLine("            panel.RowStyles.Add(new RowStyle(SizeType.Absolute, 38));");
        builder.AppendLine("            panel.Controls.Add(new Label { Text = label, Dock = DockStyle.Fill, TextAlign = ContentAlignment.MiddleLeft }, 0, row);");
        builder.AppendLine("            control.Dock = DockStyle.Fill;");
        builder.AppendLine("            control.Margin = new Padding(0, 3, 0, 3);");
        builder.AppendLine("            panel.Controls.Add(control, 1, row);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static void ConfigureButton(Button button, string text)");
        builder.AppendLine("        {");
        builder.AppendLine("            button.Text = text;");
        builder.AppendLine("            button.Height = 30;");
        builder.AppendLine("            button.Dock = DockStyle.Fill;");
        builder.AppendLine("            button.Margin = new Padding(0, 3, 0, 3);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private void AppendLog(string message)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (IsDisposed)");
        builder.AppendLine("                return;");
        builder.AppendLine("            if (InvokeRequired)");
        builder.AppendLine("            {");
        builder.AppendLine("                BeginInvoke((MethodInvoker)(() => AppendLog(message)));");
        builder.AppendLine("                return;");
        builder.AppendLine("            }");
        builder.AppendLine("            _log.AppendText($\"[{DateTime.Now:HH:mm:ss}] {message}{Environment.NewLine}\");");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        protected override async void OnFormClosing(FormClosingEventArgs e)");
        builder.AppendLine("        {");
        builder.AppendLine("            _closing = true;");
        builder.AppendLine("            _flow.Stop();");
        builder.AppendLine("            await _board.DisposeAsync();");
        builder.AppendLine("            base.OnFormClosing(e);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private sealed class PinItem");
        builder.AppendLine("        {");
        builder.AppendLine("            public PinItem(FlowPropertyOption option)");
        builder.AppendLine("            {");
        builder.AppendLine("                Label = option.Label;");
        builder.AppendLine("                Number = Convert.ToInt32(option.Value, CultureInfo.InvariantCulture);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            public string Label { get; }");
        builder.AppendLine();
        builder.AppendLine("            public int Number { get; }");
        builder.AppendLine();
        builder.AppendLine("            public override string ToString() => Label;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }
}
