#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;

namespace CodeBridge.VisualStudio.Editor
{
    internal enum ExportAction
    {
        /// <summary>A static class with RunAsync(board, ct), added to the project that contains the flow.</summary>
        AddClassToProject,

        /// <summary>A complete Program.cs (console app), added next to the flow.</summary>
        AddConsoleProgram,

        /// <summary>The class, copied to the clipboard.</summary>
        CopyClass
    }

    internal sealed class ExportedCode
    {
        public ExportedCode(string fileName, string code, bool isConsoleProgram, IReadOnlyList<string> warnings)
        {
            FileName = fileName;
            Code = code;
            IsConsoleProgram = isConsoleProgram;
            Warnings = warnings;
        }

        public string FileName { get; }
        public string Code { get; }
        public bool IsConsoleProgram { get; }
        public IReadOnlyList<string> Warnings { get; }
    }

    /// <summary>"Export C#": turns the flow into readable code that uses the SDK (generated by CodeBridge.FlowHost).</summary>
    public partial class FlowEditorControl
    {
        /// <summary>Raised when code was generated and should be added to a project (handled by the editor pane).</summary>
        internal event Action<ExportedCode>? CodeExported;

        /// <summary>Path of the .cbflow file being edited (used to name the generated class).</summary>
        internal string? FlowFilePath { get; set; }

        /// <summary>Supplies the namespace of the project that contains the flow (null: use the default).</summary>
        internal Func<string?>? NamespaceProvider { get; set; }

        private void ShowExportMenu()
        {
            var menu = new ContextMenu { PlacementTarget = ExportButton, Placement = PlacementMode.Bottom };
            menu.Items.Add(Item("Add to project as a class", null, () => _ = ExportAsync(ExportAction.AddClassToProject)));
            menu.Items.Add(Item("Add as a console app (Program.cs)", null, () => _ = ExportAsync(ExportAction.AddConsoleProgram)));
            menu.Items.Add(new Separator());
            menu.Items.Add(Item("Copy C# to the clipboard", null, () => _ = ExportAsync(ExportAction.CopyClass)));
            menu.IsOpen = true;
        }

        internal async Task ExportAsync(ExportAction action)
        {
            if (!RequireHost())
                return;

            var path = WriteTempFlow();
            if (path == null)
                return;

            var console = action == ExportAction.AddConsoleProgram;
            var className = FlowFilePath == null ? null : Path.GetFileNameWithoutExtension(FlowFilePath) + "Flow";
            var arguments = $"export --flow {HostClient.Quote(path)} --board {_document.BoardId} --mode {(console ? "console" : "class")}";
            if (!string.IsNullOrWhiteSpace(className))
                arguments += $" --class {HostClient.Quote(className!)}";

            var ns = NamespaceProvider?.Invoke();
            if (!string.IsNullOrWhiteSpace(ns))
                arguments += $" --namespace {HostClient.Quote(ns!)}";

            if (LoopCheck.IsChecked == true)
                arguments += " --loop --interval 1000";

            SetTransientStatus("Exporting to C#...");
            var messages = await HostClient.QueryAsync(arguments);

            var failure = messages.FirstOrDefault(m => m.Type == "error");
            var export = messages.FirstOrDefault(m => m.Type == "export");
            if (export == null)
            {
                ShowOutput(true);
                AppendOutput("Export to C# failed: " + (failure?.Str("message") ?? "the CodeBridge FlowHost returned nothing."));
                SetTransientStatus("Export failed (see Output)");
                return;
            }

            var code = export.Str("code") ?? string.Empty;
            var generatedClass = export.Str("className") ?? "Flow";
            var rawWarnings = ReadWarnings(export);

            foreach (var warning in rawWarnings)
                AppendOutput("Export warning: " + warning);

            if (action == ExportAction.CopyClass)
            {
                try
                {
                    Clipboard.SetText(code);
                    SetTransientStatus("C# copied to the clipboard");
                }
                catch (System.Runtime.InteropServices.ExternalException)
                {
                    ShowOutput(true);
                    AppendOutput("The clipboard is busy; try again.");
                }

                return;
            }

            var fileName = console ? "Program.cs" : generatedClass + ".cs";
            var exported = new ExportedCode(fileName, code, console, rawWarnings);
            if (CodeExported == null)
            {
                ShowOutput(true);
                AppendOutput("No project is available to receive the code. Use \"Copy C# to the clipboard\" instead.");
                return;
            }

            CodeExported.Invoke(exported);
            SetTransientStatus(rawWarnings.Count == 0 ? $"Exported {fileName}" : $"Exported {fileName} with {rawWarnings.Count} warning(s)");
        }

        /// <summary>Warnings come back as a JSON array of strings, which the generic message list does not expose.</summary>
        private static List<string> ReadWarnings(HostMessage export) => export.StringList("warnings");
    }
}
